### ISSUE TITLE
Notifaction Failed

### ISSUE THREAD

**Issue by songyawen** [leojrfs/miband2#3]
##### Error:
```python
Connecting to xxxxxxxxxxx
Connected
Enabling Auth Service notifications status...
Traceback (most recent call last):
  File "miband2_auth.py", line 138, in <module>
    main()
  File "miband2_auth.py", line 118, in main
    band = MiBand2(arg.host)
  File "miband2_auth.py", line 24, in __init__
    self.auth_notif(True)
  File "miband2_auth.py", line 34, in auth_notif
    self.writeCharacteristic(0x56, struct.pack('<2s', b'\x01\x00'), True)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 502, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 369, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 332, in _waitResp
    raise BTLEException(BTLEException.COMM_ERROR, "Error from Bluetooth stack (%s)" % errcode)
bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)
```
I run this code on RPi 3B. I am so sorry to  bother you. The handle for  characteristicr "0090" is 0057 (0056+1).

**Comment by leojrfs** [comment]
Can you be more specific?
If it is 0x57 then you should replace that 0x56 by 0x57

**Comment by vshymanskyy** [comment]
This was fixed in my fork. https://github.com/vshymanskyy/miband2-python-test
@leojrfs thanks for a good article.

**Comment by leojrfs** [comment]
@vshymanskyy thanks.
